=== clemencela/documents-structures/Exercices/exo_dtd/livre.dtd
<!ELEMENT livres (livre+)>
<!ELEMENT livre (titre,auteur,genre+,date,origine,editeur,code)>
<!ATTLIST livre rang CDATA #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date type CDATA #FIXED "parution">
<!ELEMENT origine (#PCDATA)>
<!ATTLIST origine type CDATA #REQUIRED>
<!ELEMENT editeur (#PCDATA)>
<!ELEMENT code (#PCDATA)>

=== clemencela/documents-structures/Exercices/exo_dtd/livre.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE livres SYSTEM "livre.dtd">
<livres>
<livre rang="1">
<titre>Lorenzaccio</titre>
<auteur>Alfred de Musset</auteur>
<genre>Drame romantique</genre>
<date type="parution">1834</date>
<origine type="pays">France</origine>
<editeur>Hachette</editeur>
<code>9782011689726</code>
</livre>
</livres>
